name: hw-event-proxy
on: [push, pull_request]

defaults:
  run:
    working-directory: ./hw-event-proxy

jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: tidy
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Caching conflicts happen in GHA, so just disable for now
          skip-pkg-cache: true
          skip-build-cache: true
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.42
          args: --timeout 3m0s
          working-directory: ./hw-event-proxy
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: tidy
      run: make deps-update
    - name: Run Test Scripts
      run: |
        make gha
